version: '3.5'
volumes:
  db:
services:
  url-shortener:
    build: ./..
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_USER: shortener
      DB_PASSWORD: shortener
      DB_NAME: shortener
  db:
    image: postgres
    volumes:
      - /volumes/url-shortener/postgres-data:/data/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener